"""add unique constraint to user skills

Revision ID: 1b97b056e583
Revises: 3d63530b39bb
Create Date: 2026-04-17 14:15:22.583555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b97b056e583'
down_revision: Union[str, Sequence[str], None] = '3d63530b39bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_skill'), 'user_skills', type_='unique')
    op.create_unique_constraint('uq_user_skill_level', 'user_skills', ['user_id', 'skill_id', 'level'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_skill_level', 'user_skills', type_='unique')
    op.create_unique_constraint(op.f('uq_user_skill'), 'user_skills', ['user_id', 'skill_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
