"""add hashed_password to users

Revision ID: 6e4c369a6e37
Revises: 55a4770dcb38
Create Date: 2026-04-17 08:20:59.971203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e4c369a6e37'
down_revision: Union[str, Sequence[str], None] = '55a4770dcb38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_skills_skill_id_fkey'), 'user_skills', type_='foreignkey')
    op.create_foreign_key(None, 'user_skills', 'skills', ['skill_id'], ['id'])
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.drop_constraint(None, 'user_skills', type_='foreignkey')
    op.create_foreign_key(op.f('user_skills_skill_id_fkey'), 'user_skills', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
